source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'

group :test do
  gem 'capybara'
  gem 'rspec'
  gem 'rubocop', '0.56.0'
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
end

group :database do
  gem 'pg'
end

group :extra do
end